import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/context/StoreProvider";
import Header from "./components/Header";
import { clearCart, getCart } from "./api/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart();
  const clearCartAction = async () => {
    "use server";
    return await clearCart();
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider cart={cart}>
          <Header clearCartAction={clearCartAction}/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
